### ISSUE TITLE
Cannot install with Google advanced protection

### ISSUE THREAD

**Issue by wiilkuu** [lswiderski/mi-scale-exporter#11]
Hi,

If someone using Google Advanced Protection program, cannot install 3rd party apps. Could you add app to Google Play Store or Samsung App Store?

Regards

**Comment by lswiderski** [comment]
Hi, 

I will try to release this in Google Play as an open beta. So anyone with the link will be able to install it from the store. But unfortunately I don't think it will be fully released in the store (to find by search) because of Garmin trademarks and terms, and using unofficial API.

**Comment by lswiderski** [comment]
Hi @wiilkuu 
I released the newest version in Google Play (https://github.com/lswiderski/mi-scale-exporter/releases/tag/v2.0.2)

https://play.google.com/store/apps/details?id=com.lukaszswiderski.MiScaleExporter

Could you please check it?

**Comment by wiilkuu** [comment]
Can't open the link. Get the *sth go wrong* message.

**Comment by wiilkuu** [comment]
![Uploading Screenshot_20230204_223037_Google Play Store.jpg…]()

**Comment by lswiderski** [comment]
Can you try now? The application verification process took some time for Google. But now I see it's up in the store.

**Comment by lswiderski** [comment]
@wiilkuu version 2.0.3 should be now available for everyone in Google Play
https://play.google.com/store/apps/details?id=com.lukaszswiderski.MiScaleExporter
![image](https://user-images.githubusercontent.com/2623594/226162800-39fd5797-83e2-4764-a2cd-470a54a6b530.png)
