### ISSUE TITLE
No longer syncing with Garmin (with 2FA enabled)

### ISSUE THREAD

**Issue by jkcaldwe** [lswiderski/mi-scale-exporter#14]
Since the introduction of ECG on some Garmin watches, they have made two factor authentication over email mandatory so it can no longer be disabled. This seems to be causing issues with syncing.

When I attempt to sync scale data I get an error about missing cookies but I see that the attempt is triggering a TFA code to be sent to my email. I just have no way to input that code into the app and continue syncing the data.

**Comment by lswiderski** [comment]
Thanks for the info. The 2FA is only mandatory for some watch owners? I own Fenix 6 and this morning I measured myself and uploaded the data without any problem. But I don't have 2FA enabled.

Can you change the settings?
https://www.garmin.com/en-GB/account/security/mfa/

**Comment by jkcaldwe** [comment]
Yes, I believe, at this point, it is only mandatory for some watch owners but as ECG rolls out to more watches it will become an issue unless Garmin changes their policy. 

Unfortunately I can't change the settings. It is permanent 2FA.

**Comment by lswiderski** [comment]
I did some research and unfortunately the open source projects I found that use Garmin's unofficial API have problems with 2FA and do not support it. Maybe when Garmin starts forcing more users to use 2FA, someone will find a solution to this problem.

**Comment by lswiderski** [comment]
Good News!
I just released new version with 2FA/MFA Support. 
Update in Google Play store should be available soon.

https://github.com/lswiderski/mi-scale-exporter/releases/tag/v2.1.0
