### ISSUE TITLE
Visceral fat value is rounded to integer

### ISSUE THREAD

**Issue by holecekjan** [lswiderski/mi-scale-exporter#15]
The reading of visceral fat measurement is rounded to integer instead of left in decimal number format.

Eg. Mi scale exporter reads value 12 %,
in openScale app I see value 11,52 % for the same bodymetric measurement.

All other values in Mi scale exporter are in decimal format.

**Comment by lswiderski** [comment]
That's because Garmin also rounds up visceral fat to integer numbers. So In the Garmin Connect you will see 12 no difference if you send 11.52 or 12.

**Comment by lswiderski** [comment]
I fixed this in 2.0.3 and now the MiScale Exporter get the correct decimal value. But Garmin still rounds it up
