### ISSUE TITLE
Can’t upload data

### ISSUE THREAD

**Issue by parowa92** [lswiderski/mi-scale-exporter#17]
Yello

After last update syncing no more working.
It gives error like at the screenshot.
![A0E852D1-C549-4532-9EF6-C63216014109](https://user-images.githubusercontent.com/55931722/228912378-463d3fc8-fdd5-4dbc-92a8-05f521f1dbe0.jpeg)

**Comment by lswiderski** [comment]
Hi @parowa92 
The address of the external API was changed to:  https://frog01-20364.wykr.es/ 

You can change the url in the settings or try new version. 
Google Play version can be auto updated

Google play: https://play.google.com/store/apps/details?id=com.lukaszswiderski.MiScaleExporter
APK/AAB installers: https://github.com/lswiderski/mi-scale-exporter/releases

**Comment by parowa92** [comment]
Now working like a charm!
Thx
