### ISSUE TITLE
Error 502 when try upload to Garmin cloud

### ISSUE THREAD

**Issue by h4k3r2s1** [lswiderski/mi-scale-exporter#18]
![Screenshot_2023-05-21-08-25-39-073_com lukaszswiderski MiScaleExporter-edit](https://github.com/lswiderski/mi-scale-exporter/assets/58914344/d19662bf-84cf-4622-b3c9-303894718ae5)

**Comment by lswiderski** [comment]
Hi, which version of the app do you use and what is Android Version of your phone? Is it still not working for you? Just checked the api and it works well for me.

**Comment by h4k3r2s1** [comment]
Android 13, app from Google Play

**Comment by lswiderski** [comment]
So it could have been a temporary server unavailability. Both versions are the same.
