### ISSUE TITLE
Missing cookie SESSONID

### ISSUE THREAD

**Issue by lmerhay** [lswiderski/mi-scale-exporter#20]
Hi, I have been using MiScale Exporter on Android for a while now, without any issues, however recently, whenever I am trying to upload data to Garmin, I get a "Missing cookie SESSIONID" message and the upload fails.
Is this a known issue? Can you pls let me know if you need any more specific info?
Thanks!

**Comment by lswiderski** [comment]
Hi @lmerhay !

Thanks for the report. I have the same error and it looks like Garmin has changed something in the way I log in. I'll look into it today to investigate.

**Comment by lmerhay** [comment]
Hi Łukasz, not sure if that helps to track the issue, but I also get an error message from the web app (too many requests). So yeah, something may have changed on Garmin’s end.

**Comment by lswiderski** [comment]
Status for today:
It looks like most of the open source 3rd party apps that connect to Garmin stopped working.

My findings:
Any action now require `Authorization Bearer JWT Token`,  new Cookie `JWT_FGP=`, new Header `Di-Backend: connectapi.garmin.com`

the JWT Token can be obtained under `https://connect.garmin.com/modern/di-oauth/exchange` it require 3 Cookies: `__cflb=`, `notice_behavior=implied,eu;`, `SESSIONID=`. In response header I also receive `JWT_FGP` Cookie

**Comment by SimonBaars** [comment]
I implemented a solution for this problem in related Python repositories:
- https://github.com/pe-st/garmin-connect-export/pull/96
- https://github.com/petergardfjall/garminexport/pull/104

Since I don't know much about this repo, I don't know what exact auth method is used, but I figure a similar solution could work.

**Comment by lswiderski** [comment]
@SimonBaars Thanks! I will check for sure, although I can't use Garth directly because of the project language (c#) I will reimplement the same flow

**Comment by lswiderski** [comment]
Status update: With library `OAuth.DotNetCore` I received proper oAuth1 token. I will do more tests during the weekend.

**Comment by lswiderski** [comment]
Progress update:
Login and upload of activity (weight) works already works as external lib. Now it's time to test it in Android.

https://github.com/lswiderski/GarminWeightScaleUploader/blob/master/Libs/garmin-connect-client/GarminConnectClient.Lib/Services/Client.cs

**Comment by jesuslg123** [comment]
> Progress update: Login and upload of activity (weight) works already works as external lib. Now it's time to test it in Android.
> 
> https://github.com/lswiderski/GarminWeightScaleUploader/blob/master/Libs/garmin-connect-client/GarminConnectClient.Lib/Services/Client.cs

Thanks! if you can provide the APK I could give it a try in Android.

**Comment by lswiderski** [comment]
Ok I fixed the App. It works on an emulator and my phone. Package was sent to Google Play Store to check and certificate and should be available to update within 24h.

.AAB and .APK installers are available here https://github.com/lswiderski/mi-scale-exporter/releases/tag/v2.0.8

@jesuslg123 Please check.

Any confirmation or bug report is welcome.

**Comment by jesuslg123** [comment]
> > Progress update: Login and upload of activity (weight) works already works as external lib. Now it's time to test it in Android.
> > https://github.com/lswiderski/GarminWeightScaleUploader/blob/master/Libs/garmin-connect-client/GarminConnectClient.Lib/Services/Client.cs
> 
> Thanks! if you can provide the APK I could give it a try in Android.

I don't have the scale now but I did try to upload the data from previous days and this morning and it is failing with 3 different errors, one after each attempt.

![Screenshot_20230930_170023](https://github.com/lswiderski/mi-scale-exporter/assets/7817064/eb4ffac8-cc5f-47a3-acfd-03318e01ff76)
![Screenshot_20230930_170032](https://github.com/lswiderski/mi-scale-exporter/assets/7817064/6d56beaf-ace7-4e3f-80eb-6663c061e336)
![Screenshot_20230930_170038](https://github.com/lswiderski/mi-scale-exporter/assets/7817064/31dc64c6-dfac-4f1f-afab-df0bc85968c6)


Any idea?

**Comment by lswiderski** [comment]
Thank you. I need to work on more detailed logs.  Error about expected pattern means that Garmin somehow did not authenticated you. Do you have MFA/2FA turned off? What version of Android do you use? The weight did not uploaded in background?

**Comment by jesuslg123** [comment]
Thanks for the support. Something interesting happened. I did restart the phone and worked fine this time.

May the Google play version kept running some service when I did remove to install the GitHub version? 

Now works uploading manually.

**Comment by lswiderski** [comment]
Thank you. On Scale part nothing changed so should work fine. In near future I will add some retry policy to it because I can see it can don't work randomly. 

Anyway I'm happy We won with Garmin and connection is working Again.

**Comment by SirYaro** [comment]
In my case, I was able to send weight alone. When other values are present, I'm getting the same message as @jesuslg123 on 2nd and 3rd screenshot.

**Comment by SirYaro** [comment]
Tbh I don't think this issue is resolved... :(

**Comment by lswiderski** [comment]
@SirYaro Ohh I will investigate more

**Comment by lswiderski** [comment]
@SirYaro I got the same error when I'm back to opened app. When I closed (kill) and opened again, stand on scale, get measurement and uploaded with success.

**Comment by SirYaro** [comment]
Yup. 9/10 it works like that. Which is okay-ish...? :)

I also noticed that I'm able to send data only one time. If I hit "send" second, third etc time (with different data and day) I'm getting this:
![1696093617804](https://github.com/lswiderski/mi-scale-exporter/assets/5879723/2ba5111a-c902-4447-84b3-9537e707c124)

**Comment by lswiderski** [comment]
For now I must be ok :/ In free time, I will rewrite the Garmin Connect part. But it will take some time. I wanted to release the fix asap even if it's not perfect.

**Comment by SimonBaars** [comment]
404 sounds as if it is trying to reach out to a URL unauthenticated. The new method only works for oauth2 authenticated endpoints, not for scraping webpages.
@lswiderski Do you have a list of Garmin URLs that the app tries to access?

**Comment by lswiderski** [comment]
@SimonBaars The problem was with the way of use of the Garmin client. Everytime when upload is done, method is trying to authenticate the user. On the second time, the auth headers was already there and the initial url was returning 404 (https://connect.garmin.com/modern/auth/hostname). Hotfixed it in 2.0.9 by clearing the headers of the http client.

**Comment by lswiderski** [comment]
As I can see on version 2.0.9 I don't have that problems anymore, So I'm closing this issue.
