### ISSUE TITLE
Error during the upload to Garmin (Android 14)

### ISSUE THREAD

**Issue by tarat73** [lswiderski/mi-scale-exporter#21]
![Screenshot_20231006-225723](https://github.com/lswiderski/mi-scale-exporter/assets/17885824/2de3417b-e2f5-4c87-8ba6-9ae99532719e)

**Comment by lswiderski** [comment]
Hi @tarat73 
On which version of the app do you have this error?
Does it always appear or only sometimes?

**Comment by tarat73** [comment]
Hallo,

Thank you for your devrlopment. This problem appeared yesterday. Maybe it comes with the Android 14. I have got it before yesterday on pixel 7a. Thanks

**Comment by tarat73** [comment]
Im using your 2.0.9 version.

**Comment by lswiderski** [comment]
So it was working before update to android 14? In free time I will download this version to emulator and check it

**Comment by DimaShchetinin** [comment]
I have similar issue with android 14. Before the update everything worked fine.
![Screenshot_20231011-103036](https://github.com/lswiderski/mi-scale-exporter/assets/9061553/3d641cc0-b6cd-46ec-a661-e9f41d97d93e)

**Comment by lswiderski** [comment]
@tarat73 
@DimaShchetinin 

I released version 2.0.10. It works on my Android 14 emulator and I hope it will works for you too. 
https://github.com/lswiderski/mi-scale-exporter/releases/tag/v2.0.10
It should appear in Google Play store as update in 24h.

**Comment by tarat73** [comment]
Hello,

I have now the same problem as the last post.
![Screenshot_20231016-214400](https://github.com/lswiderski/mi-scale-exporter/assets/17885824/86c6655e-addc-4476-a7ed-279197d285a8)
But I have to use 2FA because of the ECG só maybe it could be the problem.
Version: 2.0.10

BR, 
Attila

**Comment by lswiderski** [comment]
@tarat73 I'm sorry but 2FA (related issue #14 ) is not supported yet but I hope it will find time in near future to implement it.

**Comment by akorczak** [comment]
2FA is getting more and more urgent since Garmin forces it when you want to use ECG. BTW there is no way to disable it once enabled.

**Comment by lswiderski** [comment]
Yea since Garmin released the app for the ECG, 2FA will get main priority. Just updated the web version

**Comment by lswiderski** [comment]
@akorczak 2FA is now supported in the newest version of the app

**Comment by tarat73** [comment]
Hallo Lukas,

It doesn't work for me :(
Could you please check it?

Thanks
![Screenshot_20231119-123121](https://github.com/lswiderski/mi-scale-exporter/assets/17885824/6636bf49-7a98-425c-9c5e-0faf61f72521)

**Comment by lswiderski** [comment]
@tarat73 Just checked it on Emulator with Android 14 and on my own phone with Android 13 and it worked well with MFA code.
Can you check the web version? Is it working for you?
https://web-body-composition.vercel.app/

**Comment by tarat73** [comment]
Yes I could upload it by the web site:

![image](https://github.com/lswiderski/mi-scale-exporter/assets/17885824/6ee7e933-c152-4268-b6eb-4b79c4f34b3a)
I will check it again with my phone...

**Comment by tarat73** [comment]
Did you check it in the Garmin dashboard?
I don't see the upload....
![image](https://github.com/lswiderski/mi-scale-exporter/assets/17885824/1f3c4751-135b-4e26-8312-b673a232229c)

**Comment by lswiderski** [comment]
@tarat73 Strange under the hood it's the same mechanism so it should work in both places. What is your timezone? Check in 1hr if it appear in the dashboard.

this is results from my test account (last one is from real device and rest of them from emulator):
![image](https://github.com/lswiderski/mi-scale-exporter/assets/2623594/f0fd811d-f6bb-4557-8e19-7979a68767b9)

**Comment by tarat73** [comment]
Ok Im waiting and check later. I will write to you the result.... Thanks

**Comment by tarat73** [comment]
Hmmm. It is interesting. Nothing. I have checked it in the app and the web and I don't see  anything.

**Comment by lswiderski** [comment]
@tarat73 I found a bug in the API for the web version. Fix is live and now everything should works correctly.

**Comment by tarat73** [comment]
Hallo Lukas,

The web is working now. Congrat.
This was the good news. The Mobile doesn't work. :(
![Screenshot_20231120-172259](https://github.com/lswiderski/mi-scale-exporter/assets/17885824/1ccd30a0-3f57-4487-8f28-a87a7a2c4054)

**Comment by lswiderski** [comment]
@tarat73 So I really don't know where the problem is. It's the same code. In the mobile settings you can try to set "Use External API" or us Web App in your phone.
