### ISSUE TITLE
Incorect resolution

### ISSUE THREAD

**Issue by PiaSara** [lswiderski/mi-scale-exporter#22]
After the last two updates, I have problems uploading data to garmin, because after weighing, the data appears very large and it is not possible to see the whole screen, nor is it possible to scroll the window up. The data upload button is thus only visible at the very bottom and is very difficult to press (see screenshot).

I have a Realme GT2 phone (RMX3311) loaded with android 13 and the latest version of MiScale Exporter.

Otherwise the app works great!
![Screenshot_2023-11-06-04-48-15-75_e06dc87044f093fb02b07ac9aeb87c26](https://github.com/lswiderski/mi-scale-exporter/assets/150249206/5d21102a-0925-494b-9bcd-506c8701ce00)

**Comment by lswiderski** [comment]
Hi @PiaSara
I remember about your issue. I have a newborn at home, which involves a lack of time in recent days. As soon as I find a free moment I will try to fix it.

Do you have any scaling enabled, other apps are also zoomed in?

**Comment by PiaSara** [comment]
Thank you for your concern. Don't worry, I can wait. Children come first ;)

As for the error, I don't have zoom or scaling enabled in any app. Even in Mi scale exporter the whole app works normally until I press the "Go to scan" button. When the result is displayed, the image is out of scale (enlarged) as shown in the screenshot. Other screens in app are OK.

**Comment by lswiderski** [comment]
@PiaSara I couldn't reproduce it in other method than setting big values in Display Size, but I fixed the scroll so now you should be able to scroll down to buttons. Update in Google Play store should be available soon.

https://github.com/lswiderski/mi-scale-exporter/releases/tag/v2.0.10

**Comment by PiaSara** [comment]
I installed latest update.  After measuring results are still displayed big, but now I can scroll down and update normaly.

Thanks for fiksing it!
