### ISSUE TITLE
Feature Request: Ability to enter muscle mass as a percentage

### ISSUE THREAD

**Issue by Windows-Key** [lswiderski/mi-scale-exporter#23]
First of all, many thanks for making and publishing this. It is much appreciated. :)

I have a body composition scale made by Omron and I use mi-scale-exporter to manually enter the results and push them to the Garmin cloud. I had to disable MFA in order to make it function, but now it works absolutely flawlessly.

This probably isn't exactly the use case you envisioned so I hope it's okay for me to request a feature. My scale outputs body fat and muscle mass as a percentage, as opposed to an absolute value (ie. lbs or kg). 

Body fat is already exposed as a percentage in the UI. If it's not too much trouble, would be possible to give us an option to enter muscle  mass as a percentage, as well?

Many thanks in advance.

**Comment by lswiderski** [comment]
Hi @Windows-Key 

You just wrote in time. Today I got some time to do delayed work.
I finished the MFA support implementation and added an option in settings  for muscle mass as %.

Update in Google Play store should be available soon.

https://github.com/lswiderski/mi-scale-exporter/releases/tag/v2.1.0

![image](https://github.com/lswiderski/mi-scale-exporter/assets/2623594/99c46224-db37-4567-98e2-498089d72495)

**Comment by Windows-Key** [comment]
Hi Łukasz,

wow, I wasn't expecting this quick of a response, let alone an implementation. This is awesome! Thank you so, so much.
