### ISSUE TITLE
Flur exception 

### ISSUE THREAD

**Issue by Heronimonimo** [lswiderski/mi-scale-exporter#26]
When uploading I'm getting a Flur Exception. Any idea on what might cause this?

**Comment by lswiderski** [comment]
Hi @Heronimonimo 

Are you using direct upload to Garmin, or by Proxy API feature. Do you use MFA/2FA?

**Comment by Heronimonimo** [comment]
In the end this error was caused by the EULA that you have to sign before uploading weight data. After putting a number in manually an ticking the box is started working.

Thanks again for building this awesome tool!
