### ISSUE TITLE
Error code 502

### ISSUE THREAD

**Issue by dzuljo** [lswiderski/mi-scale-exporter#27]
Thanks for your work. In the past app work great. I don't use for some time and now I see error 502 when I like to upload to Garmin connect. I retipe pass but same error. My phone is galaxy S21. Thanks

**Comment by lswiderski** [comment]
Hi @dzuljo 

Does this happen all the time? 502 is gateway error/timeout and may occur when the server is overloaded. Personally, I use the app daily and haven't come across it.

**Comment by dzuljo** [comment]
Yes, all the time. 
![Screenshot_20240221_075116](https://github.com/lswiderski/mi-scale-exporter/assets/323702/ebf8ad3b-f090-4f40-a5e6-17bcd50f2b62)

**Comment by lswiderski** [comment]
Are you using direct upload or 'Use External API' in the settings?  Do you have updated app to newest version? (2.1.0)

**Comment by dzuljo** [comment]
I am using direct upload and latest version.
Thanks

**Comment by dzuljo** [comment]
Uninstall and installed again, work perfect. Thanks

**Comment by lswiderski** [comment]
I'm happy that you resolved that problem.
