### ISSUE TITLE
Mi Smart Scale 2

### ISSUE THREAD

**Issue by pafuriza** [lswiderski/mi-scale-exporter#3]
![Screenshot_2022-04-15-09-14-18-11_e06dc87044f093fb02b07ac9aeb87c26](https://user-images.githubusercontent.com/16598515/163537991-3150ab04-1f59-4eda-bc2d-d2ffb9a9ebad.jpg)
![Screenshot_2022-04-15-09-14-14-44_e06dc87044f093fb02b07ac9aeb87c26](https://user-images.githubusercontent.com/16598515/163537998-c13e8dce-1254-4375-a7f8-1e308feaa8c6.jpg)

Tested using Mi Smart Scale 2 on Oppo Reno 5 runnin Android 12. Had to manually set permissions of app in settings, else it would crash after asking location perms.

Gave error in screenshots when I finally got it to pull data off the scale.

**Comment by Neo2SHYAlien** [comment]
Confirmed. I have kind of same issue. 
![Screenshot_20220415-082537~2](https://user-images.githubusercontent.com/1681317/163538627-5e9cb2f3-d6a7-4a9f-9064-0271d88fb735.png)
In the same time openscale read data without issues

**Comment by Neo2SHYAlien** [comment]
@pafuriza try to wait until the all dashed are full and stop to blink

**Comment by lswiderski** [comment]
@pafuriza Do your scale support body composition data or only weight? Please check v1.4 I added some support for mi smart scale but I don't have device to test.

**Comment by pafuriza** [comment]
Thank you, it works now! Only for weight but I think thats all that is
supported...
Well done and thank you!
