### ISSUE TITLE
Zepp Life required after Bluetooth address

### ISSUE THREAD

**Issue by Smultie** [lswiderski/mi-scale-exporter#36]
Hi, I just got notified of this app and I'm very happy with it already.

One question: Is Zepp Life still required for this app to work if you have the Bluetooth address copied from Zepp Life?

**Comment by lswiderski** [comment]
Hi @Smultie  Nice to hear that 🙂

If you already know the BT address of the scale, a zepp app is no needed to anything. Can be turned off or even uninstalled. This app connects directly to the scale.

**Comment by Smultie** [comment]
That's great news!
