### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by maxoss** [lswiderski/mi-scale-exporter#37]
I can't upload anymore. The app crashes after the weight is taken over and stops weighing

**Comment by vojacekj** [comment]
Same here, app started to crash with new release from play store when weighing. I tried to show debug logs but nothing suspicious to see there

**Comment by fiejkamichal** [comment]
Same for me. App crash after taking weight. I tried to open "Garmin form" manually but its is also causing crash.

**Comment by sgtkt** [comment]
Same here. The app shows the weight and then crashes on trying to get additional data from the scale.

**Comment by lswiderski** [comment]
@maxoss @vojacekj @fiejkamichal @sgtkt 

Thank for report. I revert the changes that I thought did not affect this view but nevertheless something went wrong. Unfortunately Google Play do not allow for rollbacks to previous version so it will take some time (few hours) until fixed version appear in the Google Play Store. 

For manual install (but then you won't get updates form Store) is available in releases
https://github.com/lswiderski/mi-scale-exporter/releases/tag/v2.2.3

Again, thank you for fast alarm and I'm sorry for a trouble

**Comment by WojtekHenszke** [comment]
Same here. What's interesting, it does work fine on my Realme 7 phone with android 12, but it crashes on my wife's Samsung s23 (I believe she has the newest android)

**Comment by lswiderski** [comment]
Sorry guys the issue still occurs. Somehow in the .APK version it works, but in the .AAB from the Google store it no longer does.
I need to look into this more, but I won't have time until afternoon

Meanwhile you can use web version https://web-body-composition.vercel.app/

**Comment by LethalRabbit** [comment]
Amazing to see such a fast response to this issue. Thanks for all the time and effort you're putting into this @lswiderski, I'll make sure to buy you a cup of coffee after the fix is released ;)

**Comment by LethalRabbit** [comment]
Updatet as well and everything is working fine from Samsung Galaxy S21+, perfect!

**Comment by LethalRabbit** [comment]
Updated as well and everything is working fine from Samsung Galaxy S21+, perfect!
