### ISSUE TITLE
Body Composition Scale 2 Crash

### ISSUE THREAD

**Issue by dzuljo** [lswiderski/mi-scale-exporter#4]
Hello
Thanks for sharing your project.
Mi scale installed OK
Opening
Get values from MI scale
Scanning ..... and crash.

Galaxy s9+
Android 10
Thanks

**Comment by lswiderski** [comment]
Hi, thanks for a report. Try to give access to Location and Storage in Settings > Apps > MiScale Exporter > Permission.

**Comment by dzuljo** [comment]
Thanks,after add permition for storage is working.Thanks again

**Comment by lswiderski** [comment]
Your welcome
