### ISSUE TITLE
Data could not be obtained

### ISSUE THREAD

**Issue by spfmoby** [lswiderski/mi-scale-exporter#5]
Hi

I installed your app, got the scale (mi 2) address in Zeep life (where the scale is properly connected), and put all the required information on the first page (age, height, sex, address, scale type...).
When I submit, mi-scale-exporter scans, scans, and never find the scale.
I tried before weighting myself, during, after with scale screen on, after with scale screen off, no changes, it never seems to be able to connect to the scale.

The error message is:
Problem
Dada could not be obtained. try again
(twice)

Samsung S20+ Android 12

**Comment by Neo2SHYAlien** [comment]
When you step out from the scale the scale value should be stable (not to change to 0) Try to stay a little bit longer few seconds after the dashes. Also I meet issues with openscale - if you get the measurements with it later you are unable to read the miscale values and have to measure your weight again.

**Comment by spfmoby** [comment]
I tried, nothing new, still trying to connect to the scale without any success.

I tried on another phone (xiaomi note 4 on Android 9 or 10, I have to check) and the app crashes as soon as I hit the "get values from mi scale". Something related to an incorrect java string... I will try to get the exact text and maybe open another bug report about that as it is not the same error.

**Comment by Neo2SHYAlien** [comment]
Did you allow Bluetooth and other permissions of the app ? For some reason the app not request properly all needed permissions, so you have to allow them manually.

**Comment by lswiderski** [comment]
Hi,
As @Neo2SHYAlien mentioned did you give app all required Bluetooth permissions?
Can you provide a unit of weight that you use in zepp app? (kg/lbs)
And your culture settings like phone language and date/number format. 
Do you use coma or dot as number separator? (, / .)

**Comment by spfmoby** [comment]
I set all the permissions to allowed, but nothing new.

About the units, the weight is in kg.
I will test in lbs if you want but I can't do it before 10 days.

**Comment by spfmoby** [comment]
Where do you change the units??? I see no such parameter.
Also the height value is spelled hegt. Nothing very dramatic but just so you know.

**Comment by lswiderski** [comment]
@spfmoby Hi, there Is not units change available at the moment. Only Kilograms are supported.
Did you select correct scale in the form? What is the model id of your scale? What language do you use on your phone and what are your cultural settings? That could help me debug your issue.

Thanks for the feedback about typo.

**Comment by spfmoby** [comment]
The phone language is french. We use kilograms (that's what is set on the scale, in the zepp app...)
The scale is a Xiaomi Mi Body Composition Scale 2, that's of course what I selected in the app. I also tried to check the "mi smart scale" radio button instead, but same result (scanning for a long time, then error message "data could not be obtained").

**Comment by lswiderski** [comment]
May I ask if you measure yourself barefoot or in shoes/sockets? Until now the app waited for an impedance that could only be obtained when measuring barefoot. This may have resulted in the Data could not be obtained.

In v1.6 I added new Setting, Do not wait for impedance. When is set then app return value immediately after the data is stabilized. In the future I will think how to simplify this.

If this is no solution for I added another setting - Show unstabilized data. If is set, then during measurement it will show any data that app received from a scale. 

Tested on model: XMTZC02HM

Please check it out. If it still not work please provide your scale model ID and data that showed in popup (if they show up)
https://github.com/lswiderski/mi-scale-exporter/releases/tag/v1.6

**Comment by spfmoby** [comment]
It works !
I don't remember all the tests I've done before barfoot or not, as I was trying on 2 different phones/Android versions and had 2 different problems, but now, barefoot, with 1.6 version, it works.

Thanks for the fix and improved parameters.

Just to be sure of something, can you check that the male/female parameter is properly saved, becaused I noticed that if I check "female", then on next launch (app closed between), when I come back in the app, the radio button is back to male.

**Comment by lswiderski** [comment]
Thanks for response and I'm happy that works. 

Noted bug with radio buttons state.
