### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by spfmoby** [lswiderski/mi-scale-exporter#8]
Not very important, but I think the UI could be greatly improved by moving all the parameters of the "scan" page to something more like a profile page, or why not in the main parameters.
the gender, height, login, pass.... are not supposed to change between measures, so why put them here? I know there is a "bypass" option, but is makes the app more confusing.

Also maybe replace the "age" parameter with a date of birth (and then generate the age), so it never has to be changed.

**Comment by lswiderski** [comment]
Currently I'm working on convert the app from Xamarin to MAUI and I will take the suggestion into account. 

Some people don't want their garmin passwords to be saved in the 3rd party app like this, so the password for sure will stay in garmin form with option to enter it everytime without save.

**Comment by spfmoby** [comment]
Maybe on the "profile" parameter page we could specify the email, the password field and if the password field is kept empty, make a popup when the upload button is clicked (only if the password is empty). Or something a little bit like that, for example you may prefer a checkbox "always asks for the password" in the parameters so it is more clear.

**Comment by lswiderski** [comment]
all parameters are now under settings page at newest beta build
https://github.com/lswiderski/mi-scale-exporter/releases/tag/v2.0.0-beta

**Comment by spfmoby** [comment]
Great! Thank you, I think it will make things easier to understand.
I installed the 2.0.0 beta and it seems very good. I will test soon with the scale because I don't have it around me today :)

**Comment by lswiderski** [comment]
As the version 2.0.1 with new UI is now stable. I'm closing this issue.
https://github.com/lswiderski/mi-scale-exporter/releases/tag/v2.0.1

**Comment by spfmoby** [comment]
Thank you, great work!

**Comment by ablizorukov** [comment]
Hi @lswiderski 
Just wondering, I have installed the app and see the setting age instead of birth date, is that still pending to be done or will be done later?

**Comment by lswiderski** [comment]
Hi @ablizorukov 
For a moment I considered it but decided that it was not necessary. Underneath, you would have to change the date to age anyway because the scale algorithm requires age.

The only inconvenience is that once a year you have to bump up this value in the settings. But this gives the app one less sensitive data, which can be important for people who don't want to provide such data as birthdate in apps.

Best regards.
